### ISSUE TITLE
Correção de endpoint

### ISSUE THREAD

**Issue by martins-marcelo** [martins-marcelo/spring-boot-ionic-backend#2]
feature-1. O endpoint de buscar páginas de produtos exibe muitos parâmetros, além de a lista de categorias ser inputada de forma que a entrada do endpoint seja uma String a ser separada em uma lista de inteiros separados por vírgula. Seria interessante a entrada via body e não via request param, além de a lista de categorias já ser inputada em forma de lista

**Comment by matiasJoao** [comment]
Foi resolvido ja primo
